
#server port
server:
  port: 8888



# oracle config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle.coffit.site:1521:xe
    username: C##WELPAIRTEST
    password: WELPAIRTEST

# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml

logging:
  level:
    org.springframework.security: DEBUG

